### ISSUE TITLE
Error in creating Taxon object when merged_dmp is not given

### ISSUE THREAD

**Issue by pooranis** [apcamargo/taxopy#6]
Hello!  I am using taxopy v0.9.1 installed from pypi with pip. I have already downloaded and unzipped the ncbi taxonomy files, and I'm trying to follow the examples in the readme, but I get an error in creating a `Taxon` object:

```python
import taxopy

# keep_files = True necessary because otherwise will try to delete existing files
taxdb = taxopy.TaxDb(nodes_dmp="ncbi_taxonomy/nodes.dmp", names_dmp="ncbi_taxonomy/names.dmp", keep_files=True)
human = taxopy.Taxon(9606, taxdb)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/lib/python3.10/site-packages/taxopy/core.py", line 251, in __init__
    self.legacy_taxid = self.taxid in taxdb.oldtaxid2newtaxid
TypeError: argument of type 'NoneType' is not iterable
```

If I include the `merged_dmp` parameter, then it works:

```python
taxdb = taxopy.TaxDb(nodes_dmp="ncbi_taxonomy/nodes.dmp", names_dmp="ncbi_taxonomy/names.dmp", 
              merged_dmp = "ncbi_taxonomy/merged.dmp", keep_files=True)
human = taxopy.Taxon(9606, taxdb)
print(human)

root > cellular organisms > Eukaryota > Opisthokonta > Metazoa > Eumetazoa > Bilateria > Deuterostomia > Chordata > Craniata > Vertebrata > Gnathostomata > Teleostomi > Euteleostomi > Sarcopterygii > Dipnotetrapodomorpha > Tetrapoda > Amniota > Mammalia > Theria > Eutheria > Boreoeutheria > Euarchontoglires > Primates > Haplorrhini > Simiiformes > Catarrhini > Hominoidea > Hominidae > Homininae > Homo > Homo sapiens
```

The docs say `merged_dmp` should not be necessary if you are using data downloaded from NCBI.  Thanks!

**Comment by apcamargo** [comment]
Thanks for reporting the issue! I just fixed the bug and will upload a new version soon.
